services:
  rest_gate:
    image: ${REGISTRY_HOST}/rest-gate
    build:
      context: ../src
      dockerfile: ../docker/ruby/Dockerfile
      cache_from:
        - type=gha,scope=rest-gate
      cache_to:
        - type=gha,scope=rest-gate,mode=max
    ports:
      - 7000:7000
