source 'https://rubygems.org'

gem 'sinatra'
gem 'slim'
gem 'faraday'
gem 'faraday-retry', '~> 2.2'
gem 'faraday-net_http_persistent', '~> 2.0'

gem 'rack', '~> 3.1.13'
gem 'rackup', '~> 2.2.1'
gem 'falcon'

gem 'stack-service-base'

group :test do
  gem 'rspec'
  gem 'rack-test'
  gem 'async-rspec'

  gem 'simplecov'
  # gem 'simplecov-cobertura'
end
